version: '3.1'
services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=muxtar
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db

  adminer:
    image: adminer
    ports:
      - 8080:8080