# Generated by Django 4.0.3 on 2022-03-11 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_story_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='categori_id',
            new_name='category',
        ),
    ]
