# Generated by Django 4.0.3 on 2022-03-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_rename_categori_id_story_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='media/image/categories'),
        ),
        migrations.AlterField(
            model_name='story',
            name='cover_image',
            field=models.ImageField(upload_to='media/image/story_cover_image'),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(upload_to='media/image/story_images'),
        ),
    ]
