# Generated by Django 4.0.3 on 2022-04-06 13:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0004_alter_categories_image_alter_story_cover_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Story',
            new_name='Stories',
        ),
    ]
