# Generated by Django 4.0.3 on 2022-04-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_stories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(upload_to='image/categories'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='cover_image',
            field=models.ImageField(upload_to='image/story_cover_image'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(upload_to='image/story_images'),
        ),
    ]
