# Generated by Django 4.0.3 on 2022-04-10 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_alter_categories_image_alter_stories_cover_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('update_data', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='image/desc')),
                ('stories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stories.stories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
