# Generated by Django 4.0.3 on 2022-04-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stories',
            old_name='content',
            new_name='desc',
        ),
        migrations.AlterField(
            model_name='stories',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
